import {test} from 'node:test';import assert from 'node:assert/strict';import {createHandler} from '../api/analyze-food.mjs';
const env={OPENAI_API_KEY:'server-test-secret',OPENAI_MODEL:'test-vision-model',MISE_ACCESS_TOKEN:'a'.repeat(40),ALLOWED_ORIGINS:'https://mise.example'};
const body={images:['data:image/jpeg;base64,/9j/AA==']};
async function invoke(handler,overrides={}){let output;const headers={};const res={statusCode:200,setHeader:(k,v)=>headers[k]=v,end:text=>output=text};await handler({method:'POST',headers:{origin:'https://mise.example',authorization:'Bearer '+'a'.repeat(40),'content-type':'application/json'},body,...overrides},res);return {status:res.statusCode,data:output?JSON.parse(output):null,headers}}
test('API integration sends structured vision request, returns JSON',async()=>{let request;const handler=createHandler({env,fetcher:async(url,opts)=>{request={url,...opts};return {ok:true,json:async()=>({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({ingredients:[{name:'Tomate',quantity:3,unit:'Stück',confidence:.94,note:''}]})}]}]})}}});const r=await invoke(handler);assert.equal(r.status,200);assert.equal(r.data.ingredients[0].name,'Tomate');const b=JSON.parse(request.body);assert.equal(b.text.format.strict,true);assert.equal(b.store,false);assert.equal(b.input[0].content[1].type,'input_image');assert(!JSON.stringify(r.data).includes(env.OPENAI_API_KEY))});
test('Missing server configuration is honest 503',async()=>{const r=await invoke(createHandler({env:{ALLOWED_ORIGINS:env.ALLOWED_ORIGINS}}));assert.equal(r.status,503)});
test('Untrusted origin and unauthorized calls rejected',async()=>{const handler=createHandler({env});assert.equal((await invoke(handler,{headers:{origin:'https://evil.example'}})).status,403);assert.equal((await invoke(handler,{headers:{origin:'https://mise.example',authorization:'Bearer wrong'}})).status,401)});
test('Preflight works, invalid payload and methods fail',async()=>{const h=createHandler({env});assert.equal((await invoke(h,{method:'OPTIONS'})).status,204);assert.equal((await invoke(h,{method:'GET'})).status,405);assert.equal((await invoke(h,{body:{images:['https://example.com/image.jpg']}})).status,400);assert.equal((await invoke(h,{body:{images:Array(5).fill(body.images[0])}})).status,400)});
test('Refusals, malformed and incomplete model output fail safely',async()=>{for(const output of [{status:'incomplete',output:[]},{status:'completed',output:[]}]){const h=createHandler({env,fetcher:async()=>({ok:true,json:async()=>output})});assert.equal((await invoke(h)).status,502)}});
