// Render/event smoke tests with a minimal DOM stub, NOT a real browser layout test.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function app(){const nodes=new Map(),handlers={},storage=new Map(),session=new Map();function node(s){if(!nodes.has(s))nodes.set(s,{innerHTML:'',textContent:'',value:'',style:{},dataset:{},open:false,classList:{add(){},remove(){},toggle(){}},addEventListener(){},showModal(){this.open=true},close(){this.open=false},focus(){},click(){},append(){}});return nodes.get(s)}const document={querySelector:node,addEventListener:(n,fn)=>{(handlers[n]||=[]).push(fn)},createElement:t=>node(t),body:node('body'),activeElement:null};const window={addEventListener(){},scrollTo(){}};const context=vm.createContext({window,document,localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},sessionStorage:{getItem:k=>session.get(k)??null,setItem:(k,v)=>session.set(k,v)},Intl,URL,Blob,Date,Math,Set,Map,console,setTimeout:()=>1,clearTimeout(){},AbortController,FormData:class {constructor(target){this.target=target}get(k){return this.target.values[k]??null}}});for(const f of ['data/ingredients.js','data/recipes.js','js/core.js','js/vision.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),context);for(const k of ['MiseDB','MiseRecipes','MiseCore','MiseVision'])context[k]=window[k];vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/app.js'),'utf8'),context);return {context,nodes,handlers,run:s=>vm.runInContext(s,context),html:()=>node('#view').innerHTML}}
test('App boots without demo ingredients; all screens render',()=>{const a=app();assert.match(a.html(),/0 Zutaten vorhanden/);for(const p of ['inventory','recipes','favorites','home']){a.run(`go('${p}')`);assert(a.html().length>100)}assert.equal(a.run('state.inventory.length'),0)});
test('All 80 detail views, portions and steps render',()=>{const a=app();for(const r of a.context.MiseRecipes){a.run(`selected='${r.id}';portions=3;renderDetail()`);assert(a.html().includes(r.name.replace(/&/g,'&amp;')));assert.match(a.html(),/FEHLT ODER REICHT NICHT/)} });
test('Recipe DOM limited to 12 cards and meal filter combines with time',()=>{const a=app();a.run("go('recipes')");assert.equal((a.html().match(/class="recipe"/g)||[]).length,12);a.run("state.settings.meal='Frühstück';filter='Unter 20 Min.';render()");assert(a.run('recipeList().every(x=>x.r.time<=20&&(x.r.category===\'Frühstück\'||x.r.tags.includes(\'Frühstück\')))'));assert.match(a.html(),/Frühstück/)});
test('Missing paprika renders 75% and explicit shortage in card',()=>{const a=app();a.run("state.inventory=[{ingredientId:'egg',amount:4,unit:'Stück'},{ingredientId:'cheese',amount:50,unit:'g'},{ingredientId:'milk',amount:30,unit:'ml'}]");const html=a.run("card(recipeById.get('omelett'))");assert.match(html,/75 % vorhanden/);assert.match(html,/Paprika/);assert.doesNotMatch(html,/Mit deinem Vorrat möglich/)});
test('Disconnected scanner has no fake recognition',()=>{const a=app();a.run('upload()');const html=a.nodes.get('#modal').innerHTML;assert.match(html,/KI-Erkennung noch nicht verbunden/);assert.match(html,/Keine Fotoanalyse durchgeführt/);assert.equal(a.run('draft.length'),0)});
test('Autocomplete offers Tahin as custom and Olivenöl as known',()=>{const a=app();a.run("edit();renderSuggestions('Tahin')");assert.match(a.nodes.get('#suggestions').innerHTML,/Tahin.*hinzufügen/);a.run("renderSuggestions('Olivenöl')");assert.match(a.nodes.get('#suggestions').innerHTML,/olive_oil/)});
test('Unknown units never render a cookable 100% badge',()=>{const a=app();a.run("state.inventory=recipeById.get('omelett').ingredients.map(i=>({ingredientId:i.id,amount:i.amount,unit:i.id==='egg'?'Packung':i.unit}))");const html=a.run("card(recipeById.get('omelett'))");assert.match(html,/Mengen prüfen/);assert.doesNotMatch(html,/100 % vorhanden|Mit deinem Vorrat möglich/)});
